### ISSUE TITLE
Cannot highlight comment correctly

### ISSUE THREAD

**Issue by cuixiping** [antfu/wenyan-lang-vscode#11]
```
批曰。「「吾嘗觀「「算經」」之書。」」。
```
online IDE:
![image](https://user-images.githubusercontent.com/1104492/71551774-fcb57e80-2a29-11ea-8d0b-507a63f78bbf.png)

vscode:
![image](https://user-images.githubusercontent.com/1104492/71551784-3c7c6600-2a2a-11ea-997e-259163a570df.png)

**Comment by antfu** [comment]
Sorry I this seems to not supported by VSCode. I have tried to fix the grammar and not luck for that.

Here are some common language examples I have also tested out. None of them seem to support nested comments

HTML
![image](https://user-images.githubusercontent.com/11247099/71553730-57150600-2a4f-11ea-9283-0fb57d49c0d5.png)

Javascript
![image](https://user-images.githubusercontent.com/11247099/71553735-6dbb5d00-2a4f-11ea-9d24-10b644fde917.png)

C++
![image](https://user-images.githubusercontent.com/11247099/71553737-875ca480-2a4f-11ea-95aa-9811ed6b53ce.png)

Since using nested comments is not a common case. For this, I would suggest the wenyan lang itself not to use `「「` for both multiline comments and string literals.
